# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    checkLatest: true
  displayName: 'Install Node.js'



- script:  |
    
    git config --global user.email "657225485@qq.com";
    git config --global user.name "www778878net";
    npm install;
    npm run build;  
    
  displayName: 'npm install and build'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Generating Build Number"      
      $baseDate = [datetime]"01/01/2000"      
      $currentDate = $(Get-Date)      
      $interval = NEW-TIMESPAN –Start $baseDate –End $currentDate      
      $days = $interval.Days
      $Minutes=$interval.Minutes
      
      Write-Host "##vso[task.setvariable variable=buildNumber]0.0.$days.$Minutes"
      npm version ${env:BUILDNUMBER}
- task: Npm@1
  inputs:
    command: 'publish'
    publishEndpoint: 'npm'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "git push"  
      git push origin --all && git push origin --tags