#!/bin/sh

# Read the ref and branch name from stdin
while read oldrev newrev ref
do
    branch=$(echo $ref | cut -d/ -f3)
    
    # If on the develop branch, run npm script
    if [ "$branch" = "develop" ]; then
        echo "On develop branch, running npm  script..."
        cd "$(git rev-parse --show-toplevel)"
        npm run main
    fi
done