#!/bin/sh

# Read the ref and branch name from stdin
while read oldrev newrev ref
do
    branch=$(echo $ref | cut -d/ -f3)
    
    # If on the develop branch, run npm script
    if [ "$branch" = "develop" ]; then
        echo "On develop branch, running npm script..."
        cd "$(git rev-parse --show-toplevel)"
        echo "Current directory: $(pwd)"
        npm run main
        if [ $? -ne 0 ]; then
            echo "npm script failed with exit code $?"
        else
            echo "npm script finished successfully"
        fi
    fi
done