name: Build, Test

on:
  push:
    branches:
      - develop

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0 # 获取完整历史记录

      - name: Fetch main branch and check for new tags
        id: check-main-and-tags
        run: |
          git fetch origin main
          NEW_COMMITS=$(git rev-list --count origin/main..develop)
          echo "NEW_COMMITS:$NEW_COMMITS"
          echo "NEW_COMMITS=$NEW_COMMITS" >> $GITHUB_OUTPUT

          # 检查是否有新的标签
          NEW_TAGS=$(git ls-remote --tags origin | awk '{print $2}' | wc -l)
          echo "NEW_TAGS:$NEW_TAGS"
          echo "NEW_TAGS=$NEW_TAGS" >> $GITHUB_OUTPUT

          # 打印日志
          echo "Fetching main branch completed."
          echo "Checking for new tags completed."

      - name: Merge develop into main with squash
        if: steps.check-main-and-tags.outputs.NEW_TAGS != '0'
        run: |
          git config --global user.email "657225485@qq.com"
          git config --global user.name "Frieda.Hu<657225485@qq.com>"
          git checkout main
          git merge develop --squash
          # 获取倒数第二个提交的信息，并去除换行符
          SECOND_TO_LAST_COMMIT_MESSAGE=$(git log --pretty=format:'%B' -n 2 develop | tail -n +2 | tr -d '\n')
          git commit -m "$SECOND_TO_LAST_COMMIT_MESSAGE"
          git push origin main

          # 打印日志
          echo "Merging develop into main with squash completed."
          echo "Commit message used: $SECOND_TO_LAST_COMMIT_MESSAGE"